# Use local image
FROM nautical-backup

RUN \
    echo "**** Installing pacakges ****" && \
    apk add --no-cache \
    ruby-full \
    py3-pip \
    nano && \
    echo "**** Installing ruby pacakges (for tests) ****" && \
    gem install bashcov simplecov-cobertura simplecov-html

VOLUME [ "/app" ]
VOLUME [ "/tests" ]

EXPOSE 8069

ENTRYPOINT ["/init"]