
# cd .. docker build -t nautical-backup . --progress=plain --no-cache
# cd dev && docker compose up
---
version: '3'
services:
  # lifecycle:
  #   image: lifecycle
  #   container_name: lifecycle
  #   labels:
  #   - "nautical-backup.lifecycle.before.timeout=10s"
  #   - "nautical-backup.lifecycle.before=/bin/sh ./sleep.sh"
  #   - "nautical-backup.lifecycle.after=/bin/sh ./goodbye.sh"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - TZ=America/Los_Angeles
      - WATCHTOWER_SCHEDULE=0 0 4 * * * # Every day at 4am
    labels:
      - "nautical-backup.enable=true"
      # - "nautical-backup.stop-before-backup=true"
      - "nautical-backup.override-source-dir=watchtower-data"
      # - "nautical-backup.additional-folders=add1"
      # - "nautical-backup.use-default-rsync-args=false"
      - "nautical-backup.rsync-custom-args= "
      - "nautical-backup.group=your-mom"

  nautical-backup:
    # image: minituff/nautical-backup:2.0.0
    image: nautical-backup:test
    container_name: nautical-backup-test
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER-./}/dev/source:/app/source
      - ${LOCAL_WORKSPACE_FOLDER-./}/dev/destination:/app/destination 
      - ${LOCAL_WORKSPACE_FOLDER-./}/dev/config:/config 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8069:8069
    environment:
      - TZ=America/Los_Angeles
      - LOG_LEVEL=TRACE
      - BACKUP_ON_START=false
      - CRON_SCHEDULE=0 4 * * *
      - REQUIRE_LABEL=true
      - HTTP_REST_API_ENABLED=true