
# COMPOSE_BAKE=false
# cd dev && docker compose up
---
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - watchtower-data:/data/test:ro # Named volume
      # - /data/test2 # Anonymous volume
      # - ./source/watchtower:/data/watchtower:ro # Bind mount
    ports:
      - 8080:8080
    environment:
      - TZ=America/Los_Angeles
      - WATCHTOWER_SCHEDULE=0 0 4 * * * # Every day at 4am
    labels:
      - "nautical-backup.enable=true"
      - "nautical-backup.stop-timeout=2"
      # - "nautical-backup.curl.before=echo NB_EXEC_ATTACHED_TO_CONTAINER: $$NB_EXEC_ATTACHED_TO_CONTAINER"
      # - "nautical-backup.curl.before=/config/script.sh"
      # - "nautical-backup.override-source-dir=folder/watchtower"

  # docker_socket_proxy:
  #   image: tecnativa/docker-socket-proxy
  #   container_name: docker_socket_proxy
  #   ports:
  #     - 2375:2375
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     # Enable the API access to the following sections of the Docker API
  #     # https://github.com/Tecnativa/docker-socket-proxy?tab=readme-ov-file#grant-or-revoke-access-to-certain-api-sections
  #     - CONTAINERS=1
  #     - IMAGES=1
  #     - ALLOW_START=1
  #     - ALLOW_STOP=1
  #     - EXEC=1
  #     - VOLUMES=1


  nautical-backup:
    build: ../
    # container_name: nautical-backup-test
    stop_grace_period: ${NAUTICAL_STOP_GRACE_PERIOD:-1s}
    develop:
      watch:
        - action: rebuild
          path: ${LOCAL_WORKSPACE_FOLDER-./}/app
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER-./}/dev/config:/config
      - ${LOCAL_WORKSPACE_FOLDER-./}/dev/source:/app/source:ro
      - ${LOCAL_WORKSPACE_FOLDER-./}/dev/destination:/app/destination
      # - /var/lib/docker/volumes:/app/volumes:ro
      # Optional, or you can use the docker_socket_proxy service
      - /var/run/docker.sock:/var/run/docker.sock
      # - ${LOCAL_WORKSPACE_FOLDER-./}/app:/app # Allows code to be edited on the fly
    # user: 1000:1000
    ports:
      - 8069:8069
    environment:
      - TZ=America/Los_Angeles
      - LOG_LEVEL=DEBUG
      - S6_SERVICES_GRACETIME=${NAUTICAL_S6_SERVICES_GRACETIME:-250}
      - S6_KILL_GRACETIME=${NAUTICAL_S6_KILL_GRACETIME:-250}
      - BACKUP_ON_START=true
      - REPORT_FILE=false
      - CRON_SCHEDULE=* * * * *
      - STOP_TIMEOUT=2
      # - REQUIRE_LABEL=true
      - HTTP_REST_API_ENABLED=true
      - EXIT_AFTER_INIT=true
      # - RUN_ONCE=true
      - USE_DEST_DATE_FOLDER=true
      # - DEST_DATE_PATH_FORMAT=container/date
      - DEST_DATE_PATH_FORMAT=date/container
      - NUMBER_OF_BACKUPS_TO_KEEP=1
      - MIN_BACKUPS_TO_KEEP=3
      # - RETENTION_DRY_RUN=true
      # - DEST_DATE_FORMAT=Nautical Backup - %Y-%m-%d
    # entrypoint: ["sleep", "infinity"]

# volumes:
#   watchtower-data:
