
# cd .. docker build -t nautical-backup . --progress=plain --no-cache
# cd dev && docker compose up
---
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - watchtower-data:/data/test:ro # Named volume
      - /data/test2 # Anonymous volume
      - ./source/watchtower:/data/watchtower:ro # Bind mount
    ports:
      - 8080:8080
    environment:
      - TZ=America/Los_Angeles
      - WATCHTOWER_SCHEDULE=0 0 4 * * * # Every day at 4am
    labels:
      - "nautical-backup.enable=true"
      # - "nautical-backup.curl.before=echo NB_EXEC_ATTACHED_TO_CONTAINER: $$NB_EXEC_ATTACHED_TO_CONTAINER"
      # - "nautical-backup.curl.before=/config/script.sh"
      # - "nautical-backup.override-source-dir=folder/watchtower"

  # nautical-backup:
  #   image: nautical-backup:test
  #   build: ../
  #   container_name: nautical-backup-test
  #   # develop:
  #   #   watch:
  #   #     - action: rebuild
  #   #       path: ${LOCAL_WORKSPACE_FOLDER-./}/app
  #   volumes:
  #     - ${LOCAL_WORKSPACE_FOLDER-./}/dev/config:/config
  #     - ${LOCAL_WORKSPACE_FOLDER-./}/dev/source:/data/source:ro
  #     - ${LOCAL_WORKSPACE_FOLDER-./}/dev/destination:/data/destination
  #     - /var/lib/docker/volumes:/data/volumes:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ${LOCAL_WORKSPACE_FOLDER-./}/app:/app # Allows code to be edited on the fly
  #   # user: 1000:1000
  #   ports:
  #     - 8069:8069
  #   environment:
  #     - TZ=America/Los_Angeles
  #     - LOG_LEVEL=TRACE
  #     - BACKUP_ON_START=true
  #     - REPORT_FILE=false
  #     - CRON_SCHEDULE=0 4 * * *
  #     # - REQUIRE_LABEL=true
  #     - HTTP_REST_API_ENABLED=true
  #     # - RUN_ONCE=trues
  #     # - USE_DEST_DATE_FOLDER=true
  #     # - DEST_DATE_PATH_FORMAT=container/date
  #     # - DEST_DATE_FORMAT=Nautical Backup - %Y-%m-%d


volumes:
  watchtower-data: