#!/usr/bin/env bash

# The first argument will be the exit code of your service, or 256 if your service was killed by an uncaught signal.
# The second argument is only meaningful if your service was killed by an uncaught signal, and contains the number of said signal.

if test "$1" -eq 256 ; then
  e=$((128 + $2))
else
  e="$1"
fi

/app/httpd.sh stop

# Pass the exit code to S6 Overlay so we can know the exit code later.
echo "$e" > /run/s6-linux-init-container-results/exitcode