#!/usr/bin/env bash

# The first argument will be the exit code of your service, or 256 if your service was killed by an uncaught signal.
# The second argument is only meaningful if your service was killed by an uncaught signal, and contains the number of said signal.

if test "$1" -eq 256 ; then
  e=$((128 + $2))
else
  e="$1"
fi

# Function to stop your socat server
stop_socat() {
    echo "Stopping server..."
    if [[ -f /tmp/socat.pid ]]; then
        SOCAT_PID=$(cat /tmp/socat.pid)
        kill $SOCAT_PID
        rm -f /tmp/socat.pid
    fi
}

stop_socat

# Pass the exit code to S6 Overlay so we can know the exit code later.
echo "$e" > /run/s6-linux-init-container-results/exitcode