#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# source /app/logger.sh # Use the logger script

# logThis "Listening on port 8069..." "INFO" "init"
echo "INFO Listening on port 8069..."

cd /app/api

exec python3 -m uvicorn main:app --host 0.0.0.0 --port 8069 --use-colors --log-level 'warning'
#-log-level Options: 'critical', 'error', 'warning', 'info', 'debug', 'trace'. Default: 'info'.
