#!/usr/bin/with-contenv bash
# shellcheck shell=bash

source /app/logger.sh # Use the logger script

if [ "$HTTP_REST_API_ENABLED" == "false" ]; then
    logThis "Not starting REST API because HTTP_REST_API_ENABLED=false" "DEBUG" "init"
    exec sleep infinity
fi


logThis "API listening on port 8069..." "INFO" "init"

logThis "Running: exec python3 -m uvicorn api.main:app --host 0.0.0.0 --port 8069 --use-colors --log-level 'warning'" "TRACE" "init"

cd / # Do not leave this out. This next line must be run from the root directory
exec python3 -m uvicorn api.main:app --host 0.0.0.0 --port 8069 --use-colors --log-level 'warning'
#-log-level Options: 'critical', 'error', 'warning', 'info', 'debug', 'trace'. Default: 'info'.
